### ISSUE TITLE
House IPL in a standard Java package namespace

### ISSUE THREAD

**Issue by mcandre** [scireum/sirius-ipl#3]
Please move the IPL class to de.scireum.ipl, or similar, to interact better with other Java classes, IDE's, etc.

**Comment by andyHa** [comment]
As IPL cannot and must not interact with other classes of the application, it is rather a "script" than a real java class. Therefore we made this separation, which also simplifies the startup procedure.

Moving IPL to a package wouldn't provide any benefits - and IntelliJ ist quite happy with a class in the default package.
